version: '3.8'

services:
  nginx-gateway:
    image: nginx:alpine
    container_name: gateway-project
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - catalog-service
      - playlist-service
    networks:
      - music-network

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    container_name: catalog-service
    expose:
      - "8080"
    networks:
      - music-network

  playlist-service:
    build:
      context: ./playlist-service
      dockerfile: Dockerfile
    container_name: playlist-service
    expose:
      - "8080"
    networks:
      - music-network

networks:
  music-network:
    driver: bridge