version: '3.8'

services:
  # RabbitMQ - очередь сообщений
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP протокол
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - music-network

  # NGINX Gateway
  nginx-gateway:
    image: nginx:alpine
    container_name: gateway-project
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - catalog-service
      - playlist-service
    networks:
      - music-network

  # Catalog Service
  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    container_name: catalog-service
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123
    expose:
      - "8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - music-network

  # Playlist Service
  playlist-service:
    build:
      context: ./playlist-service
      dockerfile: Dockerfile
    container_name: playlist-service
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123
    expose:
      - "8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - music-network

  # Message Handler - обработчик сообщений
  message-handler:
    build:
      context: ./message-handler
      dockerfile: Dockerfile
    container_name: message-handler
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - music-network

networks:
  music-network:
    driver: bridge
